# Generated by Django 2.0.5 on 2018-05-14 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, default='0000000000', max_length=10, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('pan', models.CharField(blank=True, default='AAAAA0000A', max_length=10, null=True)),
                ('aadhar', models.CharField(blank=True, default='0000000000000000', max_length=16, null=True)),
                ('gender', models.CharField(blank=True, default='O', max_length=1, null=True)),
                ('address', models.CharField(blank=True, default='XX', max_length=100, null=True)),
                ('state', models.CharField(blank=True, default='XX', max_length=100, null=True)),
                ('zipcode', models.CharField(blank=True, default='000000', max_length=6, null=True)),
                ('folderID', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('secureKey', models.CharField(blank=True, default='', max_length=32, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='otprecord',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='userprofile.Profile'),
        ),
    ]
